elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest 
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - /etc/pki/tls/certs:/logstash/certs
    - /etc/pki/tls/private:/logstash/private
  ports:
    - "5000:5000"
  links:
    - elasticsearch
  command: logstash -f /etc/logstash/conf.d/logstash.conf
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
